FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

# Make port available to the world outside this container
EXPOSE 8501

# Run the application using Gunicorn
CMD ["streamlit", "run", "streamlit_app.py"]